namespace Arktos.WinBert.RandoopIntegration
{
    using System;
    using Microsoft.Cci;

    /// <summary>
    /// Instruments a test assembly that was generated by Randoop.
    /// </summary>
    public class RandoopTestSuiteInstrumenter
    {
        #region Public Methods
        #endregion

        #region Private Methods

        /// <summary>
        /// Returns an instrumented copy of the target TestAssembly.
        /// </summary>
        /// <param name="testAssembly">
        /// The TestAssembly to instrument.
        /// </param>
        /// <returns>
        /// An instrumented copy of the target TestAssembly.
        /// </returns>
        private IAssembly InstrumentTestAssembly(IAssembly testAssembly)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Returns an instrumented copy of the target Assembly.
        /// </summary>
        /// <param name="assembly">
        /// The assembly to instrument.
        /// </param>
        /// <returns>
        /// An instrumented copy of the target Assembly.
        /// </returns>
        private IAssembly InstrumentTargetAssembly(IAssembly assembly)
        {
            throw new NotImplementedException();
        }

        #endregion
    }
}
