namespace Arktos.WinBert.RandoopIntegration
{
    using System;
    using Arktos.WinBert.Environment;
    using Arktos.WinBert.Instrumentation;

    /// <summary>
    /// Instruments a test assembly that was generated by Randoop.
    /// </summary>
    public class RandoopTestInstrumenter : ITestInstrumenter
    {
        #region Public Methods

        /// <inheritdoc/>
        public AssemblyTarget InstrumentTests(AssemblyTarget toInstrument)
        {
            throw new NotImplementedException();
        }

        #endregion
    }
}
