namespace Arktos.WinBert.RandoopIntegration
{
    using System;
    using System.Linq;
    using AppDomainToolkit;
    using Arktos.WinBert.Testing;

    /// <summary>
    /// Executes a suite of tests generated by Randoop.
    /// </summary>
    public class RandoopTestRunner : ITestRunner
    {
        #region Fields & Constants

        private readonly string testMethodName;

        #endregion

        #region Constructors & Destructors

        public RandoopTestRunner(string testMethodName)
        {
            if (string.IsNullOrWhiteSpace(testMethodName))
            {
                throw new ArgumentException("Test method name cannot be null or whitespace!");
            }

            this.testMethodName = testMethodName;
        }

        #endregion

        #region Public Methods

        /// <inheritdoc />
        public ITestRunResult RunTests(IAssemblyTarget target, IAssemblyTarget tests)
        {
            var loader = new AssemblyLoader();
            loader.LoadAssemblyWithReferences(LoadMethod.LoadFile, target.Location);
            loader.LoadAssemblyWithReferences(LoadMethod.LoadFile, tests.Location);

            var assembly = loader.LoadAssembly(LoadMethod.LoadFile, tests.Location);
            foreach (var type in assembly.GetTypes())
            {
                var testObj = Activator.CreateInstance(type);
                var method = type.GetMethods().First(x => x.Name.Equals(this.testMethodName));
                method.Invoke(testObj, null);
            }

            return TestRunResult.Successful(@"C:\out.log");
        }

        #endregion
    }
}