namespace WinBert.Testing
{
    using System.Reflection;
    using Differencing;
    using Instrumentation;

    /// <summary>
    /// This abstract class will provide a contract for any concrete class that generates regression tests for an assembly.
    /// Note the regression designation. This is because all required methods must take the difference context into account
    /// when generating any tests. In the end, all implementing subclasses must return a fully compiled assembly with tests
    /// that can be ran on the target methods (the ones flagged as different) in the passed in assembly.
    /// </summary>
    public abstract class RegressionTestGenerator : ITestGenerator<Assembly, TestAssembly>
    {
        /// <summary>
        /// The implementation of this method should analyze the passed in assembly in the context of the difference
        /// result to determine which types and methods to generate regression tests for.
        /// </summary>
        /// <param name="assembly">The assembly to generate tests for</param>
        /// <param name="diff">The difference result context</param>
        /// <returns>A compiled test assembly with executable tests inside it.</returns>
        public abstract TestAssembly GetCompiledTests(Assembly assembly, IDifferenceResult<Assembly> diff);

        /// <summary>
        /// Takes the passed in instrumenter and uses it to instrument the test assembly generated by a call to 
        /// GetCompiledTests(assembly, diff). Override this method for more complex functionality, or for specialized
        /// implementations of the ITestInstrumenter interface.
        /// </summary>
        /// <param name="assembly">The assembly to generate tests for</param>
        /// <param name="diff">The differences result context</param>
        /// <param name="instrumenter">The test instrumenter to use when instrumenting the tests</param>
        /// <returns>A compiled test assembly with executable and instrumented tests inside it.</returns>
        public virtual TestAssembly GetCompiledTests(Assembly assembly, IDifferenceResult<Assembly> diff, ITestInstrumenter instrumenter)
        {
            return instrumenter.InstrumentTests(GetCompiledTests(assembly, diff));
        }
    }
}
