namespace Arktos.WinBert.Extensions
{
    using System.Linq;
    using System.Reflection;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// Contains extension methods for classes dealing with reflection based class members.
    /// </summary>
    public static class Members
    {
        #region Fields & Constants

        public static readonly string BackingFieldDesignation = "_BackingField";
        public static readonly string AnonymousTypeFieldDesignation = "_Field";

        #endregion

        #region Extension Methods

        /// <summary>
        /// Detects if the target member is compiler generated.
        /// </summary>
        /// <param name="info">
        /// This MemberInfo.
        /// </param>
        /// <returns>
        /// True if the compiler generated attribute is set, false otherwise.
        /// </returns>
        public static bool IsCompilerGenerated(this MemberInfo info)
        {
            return info.GetCustomAttributes(typeof(CompilerGeneratedAttribute), true).Any();
        }

        /// <summary>
        /// Detects if the target property is automatically implemented.
        /// </summary>
        /// <param name="prop">
        /// The property to test. 
        /// </param>
        /// <returns>
        /// True if the property is auto implemented, false otherwise.
        /// </returns>
        public static bool MightBeAutoGenerated(this PropertyInfo prop)
        {
            var getMethod = prop.GetGetMethod();
            var setMethod = prop.GetSetMethod();
            return (getMethod == null || getMethod.IsCompilerGenerated()) && (setMethod == null || setMethod.IsCompilerGenerated());
        }

        #endregion
    }
}
